export const textElements = [
    {
      content: "Add collaboration",
      x: 113,
      y: 155,
      fontSize: 30,
      fontFamily: "Roboto",
      fontWeight: "700",
    },
    {
      content: "to your whiteboard",
      x: 113,
      y: 190,
      fontSize: 30,
      fontFamily: "Roboto",
      fontWeight: "700",
    },
    {
      content: "with SuperViz",
      x: 113,
      y: 225,
      fontSize: 30,
      fontFamily: "Roboto",
      fontWeight: "700",
    },
    {
      content: "try",
      x: 755,
      y: 97,
      fontSize: 14,
      fontFamily: "Permanent Marker",
      fontWeight: "400",
    },
    {
      content: "comments",
      x: 733,
      y: 121,
      fontSize: 14,
      fontFamily: "Permanent Marker",
      fontWeight: "400",
    },
    {
      content: "see who",
      x: 842,
      y: 111,
      fontSize: 14,
      fontFamily: "Permanent Marker",
      fontWeight: "400",
    },
    {
      content: "is online",
      x: 838,
      y: 135,
      fontSize: 14,
      fontFamily: "Permanent Marker",
      fontWeight: "400",
    },
  ];
  